import turtle as trtl
t = trtl.Turtle()
m = trtl.Turtle()

# make background
t.pensize(5)
t.penup()
t.goto(-300,300)
t.pendown()

t.fillcolor("#ADD8E6")
t.begin_fill()
  
for _ in range(4):
  t.forward(600)
  t.right(90)
  
t.end_fill()

answer = input ("Do u want a short or tall minion?   ")
if answer == "tall":
  t.fillcolor("#F5E050")
  t.begin_fill()
  t.penup()
  t.goto(-200,50)
  t.pendown()
  t.goto(200,50)
  t.goto(200,40)
  t.goto(-200,40)
  t.goto(-200,50)
  t.end_fill()
  t.penup()
  t.goto(-100,-150)
  t.pendown()
  t.fillcolor("#F5E050")
  t.begin_fill()
  t.penup()
  t.forward(400/4)
  t.pendown()
  t.forward(20/2)
  t.circle(400/4, 90)
  t.forward(400/2)
  t.circle(400/4, 90)
  t.forward(20/2)
  t.circle(400/4, 90)
  t.forward(400/2)
  t.circle(400/4, 90)
  t.forward(20/2)
  t.penup()
  t.forward(0 + 400/4)
  t.pendown()
  t.end_fill()
  t.penup()
  t.goto(-30,-180)
  t.pendown()
  t.fillcolor("#000000")
  t.begin_fill()
  t.circle(15)
  t.penup()
  t.goto(30,-180)
  t.pendown()
  t.circle(15)
  t.end_fill()
  t.penup()
  t.fillcolor("#6F8FAF")
  t.begin_fill()
  t.goto(-100,-30)
  t.pendown()
  t.goto(110,-30)
  t.goto(100,-150)
  t.goto(-90,-150)
  t.goto(-100,-30)
  t.end_fill()



  answer = input ("Do you want hair on your minion? Yes or No?   ")
  if answer == "yes":
    t.penup()
    t.goto(-20,250)
    t.pendown()
    t.goto(-20,260)
    t.penup()
    t.goto(-10,250)
    t.pendown()
    t.goto(-10,260)
    t.penup()
    t.goto(0,250)
    t.pendown()
    t.goto(0,260)
    t.penup()
    t.goto(10,250)
    t.pendown()
    t.goto(10,260)
    t.penup()
    t.goto(20,250)
    t.pendown()
    t.goto(20,260)
  

    answer = input ("one or two eyes?   ")
    if answer == "one":
      t.penup()
      t.goto(0,100)
      t.pendown()
      t.fillcolor("#ffffff")
      t.begin_fill()
      t.circle(30)
      t.end_fill()
      t.penup()
      t.goto(0,110)
      t.pendown()
      t.fillcolor("#000000")
      t.begin_fill()
      t.circle(10)
      t.end_fill()
    if answer == "two":
      t.penup()
      t.goto(-40,100)
      t.pendown()
      t.fillcolor("#ffffff")
      t.begin_fill()
      t.circle(30)
      t.end_fill()
      t.penup()
      t.goto(40,100)
      t.pendown()
      t.fillcolor("#ffffff")
      t.begin_fill()
      t.circle(30)
      t.end_fill()
      t.penup()
      t.goto(-40,110)
      t.pendown()
      t.fillcolor("#000000")
      t.begin_fill()
      t.circle(10)
      t.end_fill()
      t.penup()
      t.goto(40,110)
      t.pendown()
      t.fillcolor("#000000")
      t.begin_fill()
      t.circle(10)
      t.end_fill()
      t.penup()
      t.goto(-30,50)
      t.pendown()
      t.goto(30,50)
      



if answer == "short": 
  t.fillcolor("#F5E050")
  t.begin_fill()
  t.penup()
  t.goto(-200,50)
  t.pendown()
  t.goto(200,50)
  t.goto(200,40)
  t.goto(-200,40)
  t.goto(-200,50)
  t.end_fill()
  t.penup()
  t.goto(-130,-150)
  t.pendown()
  t.fillcolor("#F5E050")
  t.begin_fill()
  t.penup()
  t.forward(400/4)
  t.pendown()
  t.forward(150/2)
  t.circle(400/4, 90)
  t.forward(400/2)
  t.circle(400/4, 90)
  t.forward(150/2)
  t.circle(400/4, 90)
  t.forward(400/2)
  t.circle(400/4, 90)
  t.forward(150/2)
  t.penup()
  t.forward(0 + 400/4)
  t.pendown()
  t.end_fill()
  t.penup()
  t.goto(-30,-180)
  t.pendown()
  t.fillcolor("#000000")
  t.begin_fill()
  t.circle(15)
  t.penup()
  t.goto(30,-180)
  t.pendown()
  t.circle(15)
  t.end_fill()
  t.penup()
  
  t.fillcolor("#6F8FAF")
  t.begin_fill()
  t.goto(-130,-30)
  t.pendown()
  t.goto(145,-30)
  t.goto(135,-150)
  t.goto(-120,-150)
  t.goto(-130,-30)
  t.end_fill()
  
  answer = input ("Do you want hair on your minion? Yes or No?   ")
  if answer == "yes":
    t.penup()
    t.goto(-20,250)
    t.pendown()
    t.goto(-20,260)
    t.penup()
    t.goto(-10,250)
    t.pendown()
    t.goto(-10,260)
    t.penup()
    t.goto(0,250)
    t.pendown()
    t.goto(0,260)
    t.penup()
    t.goto(10,250)
    t.pendown()
    t.goto(10,260)
    t.penup()
    t.goto(20,250)
    t.pendown()
    t.goto(20,260)
    


    answer = input ("one or two eyes?   ")
    if answer == "one":
      t.penup()
      t.goto(0,100)
      t.pendown()
      t.fillcolor("#ffffff")
      t.begin_fill()
      t.circle(30)
      t.end_fill()
      t.penup()
      t.goto(0,110)
      t.pendown()
      t.fillcolor("#000000")
      t.begin_fill()
      t.circle(10)
      t.end_fill()
    if answer == "two":
      t.penup()
      t.goto(-40,100)
      t.pendown()
      t.fillcolor("#ffffff")
      t.begin_fill()
      t.circle(30)
      t.end_fill()
      t.penup()
      t.goto(40,100)
      t.pendown()
      t.fillcolor("#ffffff")
      t.begin_fill()
      t.circle(30)
      t.end_fill()
      t.penup()
      t.goto(-40,110)
      t.pendown()
      t.fillcolor("#000000")
      t.begin_fill()
      t.circle(10)
      t.end_fill()
      t.penup()
      t.goto(40,110)
      t.pendown()
      t.fillcolor("#000000")
      t.begin_fill()
      t.circle(10)
      t.end_fill()
      t.penup()
      t.goto(-30,50)
      t.pendown()
      t.goto(30,50)




wn = trtl.Screen()
wn.mainloop()